// This file is a mechanically-cleaned decompile of Skankyboy's original
// skankyboy.smd.importer.exporter.dll (2006, .NET Framework 1.1), which
// shipped as a bundled plugin with SimPE 0.77.69 and provided Valve SMD
// export for Sims 2 meshes. The 2006 DLL cannot be loaded on .NET 8
// (TFM, architecture, and SimPE API surface have all shifted since).
//
// Cleanup applied to make the decompile compile:
//   - stripped ILSpy's ((AbstractGmdcExporter)this).X protected-access
//     upcasts (illegal in modern C#)
//   - stripped //IL_XXX: Unknown result type comment noise
//   - wrapped negative int -> ElementIdentity casts in unchecked((uint)-N)
//
// Autogenerated variable names (num, val, flag, array, text) are
// preserved intentionally to minimize divergence from working code.
// Round-trip export/import was validated end-to-end before commit;
// semantic renaming is deferred so future edits can rename
// incrementally as they touch each section.
//
// Magic-number decode for the more opaque ElementIdentity comparisons:
//   -1149040725 = 0xBB8307AB = UVCoordinate
//    1559416801 = 0x5CF2CFE1 = MorphVertexDelta
//    -881902998 = 0xCB6F3A6A = NormalMorphDelta
//     -69795567 = 0xFBD70111 = BoneAssignment
//    1003946245 = 0x3BD70105 = BoneWeights

using System;
using System.Collections;
using System.IO;
using System.Text;
using System.Windows.Forms;
using SimPe.Geometry;

namespace SimPe.Plugin.Gmdc.Exporter;

public class GmdcExportToSmd : AbstractGmdcExporter
{
	public override string FileExtension => ".smd";

	public override string FileDescription => "Smd Object";

	public override string Author => "Skankyboy";

	public GmdcExportToSmd(GeometryDataContainer gmdc, GmdcGroups groups)
		: base(gmdc, groups)
	{
	}

	public GmdcExportToSmd(GeometryDataContainer gmdc)
		: base(gmdc)
	{
	}

	public GmdcExportToSmd()
	{
	}

	protected override void InitFile()
	{
		if (Groups.Length > 1)
		{
			throw new Warning("Too Much Meshes Selected", "You've selected too much meshes\nSmd File only support 1 mesh per file");
		}
		if (Groups.Length < 1)
		{
			throw new Warning("No Mesh Selected", "You need to select one mesh");
		}
	}

	private Vector3f Correct(Vector3f t, object cor)
	{
		if (cor == null)
		{
			return t;
		}
		if (cor is Quaternion)
		{
			return t;
		}
		if (!(cor is Vector3f))
		{
			return t;
		}
		return t + (Vector3f)cor;
	}

	private Quaternion Correct(Quaternion t, object cor)
	{
		if (cor == null)
		{
			return t;
		}
		if (!(cor is Quaternion))
		{
			return t;
		}
		return t * (Quaternion)cor;
	}

	protected override void ProcessGroup()
	{
		int num = 0;
		foreach (object item in (ArrayList)(object)Link.ReferencedElement)
		{
			int num2 = (int)item;
			if ((int)Gmdc.Elements[num2].Identity == -1149040725)
			{
				num = num2;
				break;
			}
		}
		GmdcElement val = Gmdc.Elements[num];
		int num3 = 0;
		int num4 = 0;
		int num5 = 0;
		int num6 = 0;
		bool flag = false;
		foreach (object item2 in (ArrayList)(object)Link.ReferencedElement)
		{
			int num7 = (int)item2;
			if ((int)Gmdc.Elements[num7].Identity == 1559416801 && Gmdc.Elements[num7].GroupId == 0)
			{
				num3 = num7;
			}
			if ((int)Gmdc.Elements[num7].Identity == -881902998 && Gmdc.Elements[num7].GroupId == 0)
			{
				num4 = num7;
			}
			if ((int)Gmdc.Elements[num7].Identity == 1559416801 && Gmdc.Elements[num7].GroupId == 1)
			{
				num5 = num7;
			}
			if ((int)Gmdc.Elements[num7].Identity == -881902998 && Gmdc.Elements[num7].GroupId == 1)
			{
				num6 = num7;
			}
		}
		GmdcElement val2 = Gmdc.Elements[num3];
		GmdcElement val3 = Gmdc.Elements[num4];
		GmdcElement val4 = Gmdc.Elements[num5];
		GmdcElement val5 = Gmdc.Elements[num6];
		string caption = "1 Morph Mesh Founded";
		string text = "Do you want to export Morph Mesh ??";
		if (num5 > 0)
		{
			caption = "2 Morph Meshes Founded";
			text = "Do you want to export Morph Meshes ??";
		}
		if (num3 > 0)
		{
			switch (MessageBox.Show(text, caption, MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button1))
			{
			case DialogResult.Yes:
				flag = true;
				break;
			case DialogResult.No:
				flag = false;
				break;
			case DialogResult.Ignore:
				flag = false;
				break;
			}
		}
		else
		{
			flag = false;
		}
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("version 1 \r\n");
		IntArrayList val6 = new IntArrayList();
		Hashtable hashtable = new Hashtable();
		Hashtable hashtable2 = new Hashtable();
		Hashtable hashtable3 = new Hashtable();
		GmdcElement val7 = Link.FindElementType((ElementIdentity)unchecked((uint)-69795567));
		GmdcElement val8 = Link.FindElementType((ElementIdentity)1003946245);
		if (val7 != null)
		{
			val6 = Gmdc.SortJoints();
			hashtable = Gmdc.LoadJointRelationMap();
			if (CorrectJointSetup)
			{
				foreach (object item3 in (ArrayList)(object)val6)
				{
					int num8 = (int)item3;
					if (num8 >= Gmdc.Model.Transformations.Length)
					{
						break;
					}
					string name = Gmdc.Joints[num8].Name;
					if (name.EndsWith("_rot"))
					{
						string text2 = name.Substring(0, name.Length - 4) + "_trans";
						if (Gmdc.Joints.Contains(text2))
						{
							hashtable3[name] = Gmdc.Joints[num8].AssignedTransformNode.Translation.GetInverse();
							hashtable3[text2] = Gmdc.Joints[num8].AssignedTransformNode.Translation;
						}
					}
					else if (name.EndsWith("_trans"))
					{
						string text3 = name.Substring(0, name.Length - 6) + "_rot";
						if (Gmdc.Joints.Contains(text3))
						{
							hashtable2[name] = Gmdc.Joints[num8].AssignedTransformNode.Rotation.GetInverse();
							hashtable2[text3] = Gmdc.Joints[num8].AssignedTransformNode.Rotation;
						}
					}
				}
			}
		}
		stringBuilder.Append("nodes \r\n");
		int num9 = 0;
		int num10 = 0;
		if (val7 != null)
		{
			string[] array = new string[((ArrayList)(object)val6).Count];
			foreach (object item4 in (ArrayList)(object)val6)
			{
				int num11 = (int)item4;
				int num12 = 0;
				if (num11 >= Gmdc.Model.Transformations.Length)
				{
					break;
				}
				array[num9] = Gmdc.Joints[num11].Name;
				for (int i = 0; i < Group.UsedJoints.Length; i++)
				{
					if (Group.UsedJoints[i] == num11)
					{
						num12 = i;
						break;
					}
				}
				if (hashtable.ContainsKey(num11))
				{
					int num13 = (int)hashtable[num11];
					if (num13 != -1)
					{
						int num14 = 0;
						string[] array2 = array;
						foreach (string text4 in array2)
						{
							if (text4 == Gmdc.Joints[num13].Name)
							{
								break;
							}
							num14++;
						}
						stringBuilder.Append(num9 + " \"" + array[num9] + "\" " + num14 + " \r\n");
					}
					else
					{
						stringBuilder.Append(num9 + " \"" + array[num9] + "\" -1 \r\n");
					}
				}
				else
				{
					stringBuilder.Append(num9 + " \"" + array[num9] + "\" -1 \r\n");
				}
				num9++;
			}
			stringBuilder.Append(num9 + " \"SmdMiscBone\" -1 \r\n");
			num10 = num9;
			num9++;
		}
		stringBuilder.Append(num9 + " \"Name-" + Group.Name + "\" -1 \r\n");
		stringBuilder.Append("end \r\n");
		int[] array3 = new int[256];
		if (val7 != null)
		{
			for (int k = 0; k < 256; k++)
			{
				array3[k] = num10;
			}
			for (int l = 0; l < Group.UsedJoints.Length; l++)
			{
				int num15 = Group.UsedJoints[l];
				for (int m = 0; m < ((ArrayList)(object)val6).Count; m++)
				{
					if (val6[m] == num15)
					{
						num15 = m;
						break;
					}
				}
				array3[l] = num15;
			}
		}
		Vector3f v = new Vector3f(0.0, 0.0, 0.0);
		stringBuilder.Append("skeleton \r\n");
		stringBuilder.Append("time 0 \r\n");
		num9 = 0;
		if (val7 != null)
		{
			foreach (object item5 in (ArrayList)(object)val6)
			{
				int num16 = (int)item5;
				if (Gmdc.Joints[num16].AssignedTransformNode != null)
				{
					Vector3f val9 = Gmdc.Joints[num16].AssignedTransformNode.Translation;
					if (CorrectJointSetup)
					{
						val9 = Correct(val9, hashtable3[Gmdc.Joints[num16].Name]);
					}
					val9 = Component.TransformScaled(val9);
					Quaternion val10 = Gmdc.Joints[num16].AssignedTransformNode.Rotation;
					if (CorrectJointSetup)
					{
						val10 = Correct(val10, hashtable2[Gmdc.Joints[num16].Name]);
					}
					Vector3f axis = val10.Axis;
					axis = Component.Transform(axis);
					val10 = Quaternion.FromAxisAngle(axis, val10.Angle);
					axis = val10.GetEulerAngles();
					stringBuilder.Append(num9 + " " + ((Vector2f)val9).X.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + ((Vector2f)val9).Y.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + val9.Z.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + ((Vector2f)axis).X.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + ((Vector2f)axis).Y.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + axis.Z.ToString("N6", AbstractGmdcExporter.DefaultCulture) + "\r\n");
				}
				else
				{
					stringBuilder.Append(num9 + " " + WriteVector(v) + WriteVector(v) + "\r\n");
				}
				num9++;
			}
			stringBuilder.Append(num9 + " " + WriteVector(v) + WriteVector(v) + "\r\n");
			num9++;
		}
		stringBuilder.Append(num9 + " " + WriteVector(v) + WriteVector(v) + "\r\n");
		stringBuilder.Append("end \r\n");
		stringBuilder.Append("triangles \r\n");
		base.writer.Write(stringBuilder.ToString());
		StringBuilder stringBuilder2 = new StringBuilder();
		StringBuilder stringBuilder3 = new StringBuilder();
		for (int n = 0; n < ((ArrayList)(object)Group.Faces).Count; n++)
		{
			StringBuilder stringBuilder4 = new StringBuilder();
			StringBuilder stringBuilder5 = new StringBuilder();
			StringBuilder stringBuilder6 = new StringBuilder();
			StringBuilder stringBuilder7 = new StringBuilder();
			int num17 = Group.Faces[n];
			int elementNr = Link.GetElementNr(VertexElement);
			Vector3f val11 = new Vector3f((double)Link.GetValue(elementNr, num17).Data[0], (double)Link.GetValue(elementNr, num17).Data[1], (double)Link.GetValue(elementNr, num17).Data[2]);
			val11 = Component.TransformScaled(val11);
			stringBuilder4.Append("0 " + WriteVector(val11));
			if (flag && num3 > 0)
			{
				int elementNr2 = Link.GetElementNr(val2);
				Vector3f val12 = new Vector3f((double)Link.GetValue(elementNr2, num17).Data[0], (double)Link.GetValue(elementNr2, num17).Data[1], (double)Link.GetValue(elementNr2, num17).Data[2]);
				val12 = Component.TransformScaled(val12);
				val12 = val11 + val12;
				stringBuilder5.Append("0 " + WriteVector(val12));
			}
			if (flag && num5 > 0)
			{
				int elementNr3 = Link.GetElementNr(val4);
				Vector3f val13 = new Vector3f((double)Link.GetValue(elementNr3, num17).Data[0], (double)Link.GetValue(elementNr3, num17).Data[1], (double)Link.GetValue(elementNr3, num17).Data[2]);
				val13 = Component.TransformScaled(val13);
				val13 = val11 + val13;
				stringBuilder6.Append("0 " + WriteVector(val13));
			}
			int elementNr4 = Link.GetElementNr(NormalElement);
			Vector3f val14 = new Vector3f((double)Link.GetValue(elementNr4, num17).Data[0], (double)Link.GetValue(elementNr4, num17).Data[1], (double)Link.GetValue(elementNr4, num17).Data[2]);
			val14 = Component.TransformNormal(val14);
			stringBuilder4.Append(WriteVector(val14));
			if (flag && num3 > 0)
			{
				if (val3 == null || val3.Values.Length < 1)
				{
					stringBuilder5.Append(WriteVector(val14));
				}
				else
				{
					int elementNr5 = Link.GetElementNr(val3);
					Vector3f val15 = new Vector3f((double)Link.GetValue(elementNr5, num17).Data[0], (double)Link.GetValue(elementNr5, num17).Data[1], (double)Link.GetValue(elementNr5, num17).Data[2]);
					val15 = Component.TransformNormal(val15);
					val15 = val14 + val15;
					stringBuilder5.Append(WriteVector(val15));
				}
			}
			if (flag && num5 > 0)
			{
				if (val5 == null || val5.Values.Length < 1)
				{
					stringBuilder6.Append(WriteVector(val14));
				}
				else
				{
					int elementNr6 = Link.GetElementNr(val5);
					Vector3f val16 = new Vector3f((double)Link.GetValue(elementNr6, num17).Data[0], (double)Link.GetValue(elementNr6, num17).Data[1], (double)Link.GetValue(elementNr6, num17).Data[2]);
					val16 = Component.TransformNormal(val16);
					val16 = val14 + val16;
					stringBuilder6.Append(WriteVector(val16));
				}
			}
			if (val != null)
			{
				int elementNr7 = Link.GetElementNr(val);
				stringBuilder7.Append(Link.GetValue(elementNr7, num17).Data[0].ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + (1f - Link.GetValue(elementNr7, num17).Data[1]).ToString("N6", AbstractGmdcExporter.DefaultCulture) + " ");
			}
			else
			{
				stringBuilder7.Append(0f.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + 0f.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " ");
			}
			if (val7 != null)
			{
				string text5 = "";
				int realIndex = Link.GetRealIndex(elementNr, num17);
				realIndex = ((GmdcElementValueOneInt)val7.Values[realIndex]).Value;
				byte[] bytes = BitConverter.GetBytes(realIndex);
				byte[] array4 = bytes;
				foreach (byte value in array4)
				{
					int num19 = Convert.ToInt16(value);
					if (num19 < 255)
					{
						text5 = text5 + " " + array3[num19];
					}
				}
				string text6 = "";
				int elementNr8 = Link.GetElementNr(val8);
				GmdcElementValueBase value2 = Link.GetValue(elementNr8, num17);
				float num20 = 0f;
				float[] data = value2.Data;
				for (int num21 = 0; num21 < data.Length; num21++)
				{
					float num22 = data[num21];
					text6 = text6 + " " + num22.ToString("N6", AbstractGmdcExporter.DefaultCulture);
					num20 += num22;
				}
				num20 = 1f - num20;
				if (num20 < 0f)
				{
					num20 = 0f;
				}
				text6 = text6 + " " + num20.ToString("N6", AbstractGmdcExporter.DefaultCulture);
				string[] array5 = text5.Split(" ".ToCharArray());
				string[] array6 = text6.Split(" ".ToCharArray());
				stringBuilder7.Append((array5.Length - 1).ToString());
				for (int num23 = 1; num23 < array5.Length; num23++)
				{
					stringBuilder7.Append(" " + array5[num23] + " " + array6[num23]);
				}
			}
			if (n % 3 == 0)
			{
				base.writer.WriteLine("map.bmp");
				base.writer.WriteLine(stringBuilder4.ToString() + stringBuilder7.ToString());
				stringBuilder2.Append("map.bmp\r\n" + stringBuilder5.ToString() + stringBuilder7.ToString() + "\r\n");
				stringBuilder3.Append("map.bmp\r\n" + stringBuilder6.ToString() + stringBuilder7.ToString() + "\r\n");
			}
			else
			{
				base.writer.WriteLine(stringBuilder4.ToString() + stringBuilder7.ToString());
				stringBuilder2.Append(stringBuilder5.ToString() + stringBuilder7.ToString() + "\r\n");
				stringBuilder3.Append(stringBuilder6.ToString() + stringBuilder7.ToString() + "\r\n");
			}
		}
		base.writer.WriteLine("end");
		stringBuilder2.Append("end \r\n");
		stringBuilder3.Append("end \r\n");
		if (flag && num3 > 0)
		{
			string fileName = FileName;
			fileName = fileName.Substring(0, fileName.Length - 4) + "-morph.smd";
			StreamWriter streamWriter = new StreamWriter(File.Create(fileName));
			streamWriter.Write(stringBuilder.ToString());
			streamWriter.Write(stringBuilder2.ToString());
			streamWriter.Close();
		}
		if (flag && num5 > 0)
		{
			string fileName2 = FileName;
			fileName2 = fileName2.Substring(0, fileName2.Length - 4) + "-morph2.smd";
			StreamWriter streamWriter2 = new StreamWriter(File.Create(fileName2));
			streamWriter2.Write(stringBuilder.ToString());
			streamWriter2.Write(stringBuilder3.ToString());
			streamWriter2.Close();
		}
	}

	protected override void FinishFile()
	{
	}

	private string WriteVector(Vector3f v)
	{
		return ((Vector2f)v).X.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + ((Vector2f)v).Y.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " " + v.Z.ToString("N6", AbstractGmdcExporter.DefaultCulture) + " ";
	}
}
