<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>theos.gbct.plugin</AssemblyName>
    <RootNamespace>SimPe.Plugin</RootNamespace>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AdvancedForms\AdvancedForms.csproj" />
    <ProjectReference Include="..\NetDocks\NetDocks.csproj" />
    <ProjectReference Include="..\SimPE.Clst\SimPE.Clst.csproj" />
    <ProjectReference Include="..\SimPE.Filehandlers\SimPE.Filehandlers.csproj" />
    <ProjectReference Include="..\SimPE.Helper\SimPE.Helper.csproj" />
    <ProjectReference Include="..\SimPE.Interfaces\SimPE.Interfaces.csproj" />
    <ProjectReference Include="..\SimPE.Packages\SimPE.Packages.csproj" />
    <ProjectReference Include="..\SimPE.RCOL\SimPE.RCOL.csproj" />
    <ProjectReference Include="..\SimPE.Scenegraph\SimPE.Scenegraph.csproj" />
    <ProjectReference Include="..\SimPE.Splash\SimPE.Splash.csproj" />
    <ProjectReference Include="..\SimPE.WorkSpaceHelper\SimPE.WorkSpaceHelper.csproj" />
  </ItemGroup>
</Project>
