<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CCB.Math</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Classless.Hasher">
      <HintPath>../../../../../../../../Users/catherinegramze/Library/Developer/Sims2CollectionCreator2/Classless.Hasher.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>